### PR TITLE
Interpretor with main and evaluation function

### PR DESCRIPTION
**Pull request by LukaShvangiradze**
Extend the if statements

### CODE REVIEW

**Comment by LukaShvangiradze** [comment]
So, I have removed yesterday's code due to its functionality.

**Comment by Talgami** [comment]
How do we extend the if statements?

**Comment by LukaShvangiradze** [comment]
Let's split up tasks. I have the main code and a evaluation function which will see what orders are we dealing with

**Comment by Talgami** [comment]
So, who does what?

**Comment by Archi-lee-Sun** [comment]
i will handled DIM and if function

**Pull request merged**
